### PR TITLE
Fix two link URLs of "index.md"

### PR DESCRIPTION
**Pull request by PINTO0309**
1st_edition/power_on -> 1st_edition/power_on **.md**
alpha_edition/power_on -> alpha_edition/power_on **.md**

### CODE REVIEW

**Comment by LattePanda** [comment]
Dear Pinto0309,

Really thanks for your contribution and commit. Actually the original links just work. Because you change the files name so it cause the linking issue. 

Look forward to see more content suggestion and contribution from u! 

Thanks for your efforts!

**Comment by PINTO0309** [comment]
@LattePanda 
As it is, "HTTP 404 error" occurs.
screenshot 2018-11-15 06 07 04
screenshot 2018-11-15 06 07 30

**Comment by LattePanda** [comment]
Please check the released docs here - http://docs.lattepanda.com/

**Comment by PINTO0309** [comment]
Thank you.

**Pull request closed without merging**
