### PR TITLE
Update set_up_windows_host.md

### PR DESCRIPTION
**Pull request by mattuna15**
Added change to reflect set up script not detecting the streaming cable. Please check name of device in device manager and amend accordingly.

### CODE REVIEW

**Comment by tyjjr** [comment]
Hi mattuna15
Thanks for your great help. i have a few quesiton:
1. What language did you choose for your operating system?
2. What is the name of the streaming cable in your device manager?
Technically, "Remote NDIS" is designed to accommodate multiple languages. "Remote NDIS Compatible Device" contains "Remote NDIS" and should be retrieved.

**Comment by mattuna15** [comment]
@tyjjr Hi, United Kingdom English. It definitely did not work until I put the whole device name in.

**Comment by tyjjr** [comment]
Thanks, sounds weird, we use "find" in the script, should be able to check the whole name and find the same part, can you confirm the name in your device manager contain "Remote NDIS"?
and is the device a LattePanda or not?

**Comment by mattuna15** [comment]
@tyjjr hi yes. Lattepanda, 
screen shot 2019-01-07 at 11 01 45

**Comment by LattePanda** [comment]
> @tyjjr hi yes. Lattepanda,
> screen shot 2019-01-07 at 11 01 45

Can u please kindly provide further update about this topic? Thanks!

**Comment by LattePanda** [comment]
Merged your tips anyway. ;)

**Pull request merged**
